<<<<<<< HEAD
theme: jekyll-theme-leap-day
title: Iftitakhul Zakiah
email: iftitakhulzakiyah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sebaik-baiknya manusia ialah manusia yang bermanfaat bagi makhluk lain
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://iftitakhulzakiah.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: iftizaaa
github_username:  IftitakhulZakiah

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
=======
theme: jekyll-theme-leap-day
